### ISSUE TITLE
missing dependencies in the setup

### ISSUE THREAD

**Issue by arivers** [zhangys11/pyCLAMs#6]
I wanted to let you know that when I installed `cla` from PyPI there were a few required  packages that were not specified by the setup or requirements files:

1. `pyNNRW`
2. `h5py`
3. `qsi_tk` (which on my system required cmake)

**Comment by zhangys11** [comment]
Now this should be fixed. 
Try 2.2.0

**Comment by arivers** [comment]
Thanks!
